[node.logging]

# Log to standard error in addition to the log file
# type:bool
log_to_cerr = false

[node.websocket]

# WebSocket server bind address
# type:string,ip
address = "::ffff:0.0.0.0"

[rpc]

# Enable or disable RPC
# type:bool
enable = true
